// <auto-generated />
namespace MovieLibrary.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class R2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(R2));
        
        string IMigrationMetadata.Id
        {
            get { return "201606070607508_R2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
